server.port: 9900

spring:
  application.name: rest-api
  cloud.config.discovery.enabled: true

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/

ribbon.http.client.enabled: false

logging.level:
  org.springframework: info

temp.remark: 'Profile (${spring.profiles:default}): ${server.port} 서버입니다 ^^'
---
spring.profiles: a1
server.port: 9901

---
spring.profiles: a2
server.port: 9902

---
spring.profiles: a3
server.port: 9903